from typing import overload


class Grid:
    default_width: int
    default_height: int

    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, a: int) -> None: ...
    @overload
    def __init__(self, a: int, b: int) -> None: ...
    @overload
    def __init__(self, *, width: int) -> None: ...
    @overload
    def __init__(self, *, height: int) -> None: ...
    @overload
    def __init__(self, *, width: int, height: int) -> None: ...

    @overload
    def snap(self, r_x: int, r_y: int) -> tuple[int, int]: ...
    @overload
    def snap(self, r_point: tuple[int, int]) -> tuple[int, int]: ...

